### PR TITLE
Updating for CRAN resubmission

### PR DESCRIPTION
**Pull request by csim063**
Main change is rebasing with main to ensure consistency and then minor tweak to description folder. This should mean CRAN branch is now showing version 1.0.3.

Actions seem to be failing https://github.com/r-spatialecology/spectre/actions/runs/3473914287 not entirely sure why maybe one of you know. Error is [Run C++ benchmark](https://github.com/r-spatialecology/spectre/actions/runs/3473914287/jobs/5806483112#step:1:35)
Unable to resolve action `r-lib/actions@master`, unable to find version `master`

### CODE REVIEW

**Comment by mhesselbarth** [comment]
6e9246e might fix the error...lets see

**Comment by mhesselbarth** [comment]
[ba872d2](https://github.com/r-spatialecology/spectre/commit/ba872d205f6fe67dd24708805603e4cc9c7bd401)
There still is an error. At least the setup-r step runs now, but there seems to be an issue with the secret tokens. I tried to add the `env:`, but if that doesn't work, @bitbacchus probably should have a look

**Comment by mhesselbarth** [comment]
@csim063 All CI checks run again

**Comment by mhesselbarth** [comment]
Wait...dont you need to merge main into CRAN :D Just seeing this now

**Comment by csim063** [comment]
Opened a revert request just in case but I am pretty sure we were working on the CRAN branch with the newest updates correct? So shouldn't it be merging CRAN in to main then?

**Comment by mhesselbarth** [comment]
Oh, I definitely lost the overview to a degree :D If we all pushed directly to CRAN, sure. Basically just make sure both branches are identical and include the most recent changes 👍

**Pull request merged**
